In [ ]:
import pandas as pd

df = pd.read_csv('../data/bronze/IMDB Dataset.csv')

df.head(10)

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive
5  Probably my all-time favorite movie, a story o...  positive
6  I sure would like to see a resurrection of a u...  positive
7  This show was an amazing, fresh & innovative i...  negative
8  Encouraged by the positive comments about this...  negative
9  If you like original gut wrenching laughter yo...  positive

In [44]:
text_col = "review"

df[text_col] = df[text_col].astype(str)
empty = df[text_col].str.strip().eq("") | df[text_col].isna()
dup = df.duplicated(subset=[text_col])

empty.sum(), dup.sum()

(0, 418)

In [45]:
y_col="sentiment"

df[y_col].value_counts(normalize=True) # 50% positive 50% negative --> highly balanced

sentiment
positive    0.5
negative    0.5
Name: proportion, dtype: float64

In [ ]:
s = df[text_col].fillna("").astype(str)
df["n_words"] = s.str.split().str.len()
df["n_chars"] = s.str.len()

df[["n_words","n_chars"]].describe(percentiles=[.5,.9,.95,.99]).T
# ! what does this do exactly ????

,count,mean,std,min,50%,90%,95%,99%,max
n_words,50000.0,231.15694,171.343997,4.0,173.0,451.0,590.0,908.00,2470.0
n_chars,50000.0,1309.43102,989.728014,32.0,970.0,2581.0,3391.0,5179.01,13704.0

In [47]:
import re

def clean_for_sentiment(t: str) -> str:
    t = str(t).lower()

    # to remove urls
    t = re.sub(r"http\S+|www\.\S+", " ", t)

    # to remove html tags
    t = re.sub(r"<.*?>", " ", t)

    # to keep punctuation, just normalize repeated spaces
    t = re.sub(r"\s+", " ", t).strip()
    return t

df["review"] = df[text_col].apply(clean_for_sentiment)
df["review"] = df["review"].str.lower()
df[["review"]].head()

                                              review
0  one of the other reviewers has mentioned that ...
1  a wonderful little production. the filming tec...
2  i thought this was a wonderful way to spend ti...
3  basically there's a family where a little boy ...
4  petter mattei's "love in the time of money" is...

In [48]:
df.head()

,review,sentiment,n_words,n_chars
0,one of the other reviewers has mentioned that ...,positive,307,1761
1,a wonderful little production. the filming tec...,positive,162,998
2,i thought this was a wonderful way to spend ti...,positive,166,926
3,basically there's a family where a little boy ...,negative,138,748
4,"petter mattei's ""love in the time of money"" is...",positive,230,1317

In [50]:
df.to_csv("../data/silver/cleaned_imdb.csv")