In [3]:
import pandas as pd
from pathlib import Path

RAW_PATH = "../data/raw/IMDB Dataset.csv"
CLEANED_PATH = "../data/clean/cleaned_imdb.csv"

Path("../data/clean").mkdir(parents= True, exist_ok=True)


df = pd.read_csv(RAW_PATH)

df.head(10)

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive
5  Probably my all-time favorite movie, a story o...  positive
6  I sure would like to see a resurrection of a u...  positive
7  This show was an amazing, fresh & innovative i...  negative
8  Encouraged by the positive comments about this...  negative
9  If you like original gut wrenching laughter yo...  positive

In [4]:
# checking for empty strings and duplicates

text_col = "review"

df[text_col] = df[text_col].astype(str)
empty = df[text_col].str.strip().eq("") | df[text_col].isna()
dup = df.duplicated(subset=[text_col])

empty.sum(), dup.sum()

(0, 418)

In [5]:
y_col="sentiment"

df[y_col].value_counts(normalize=True) # 50% positive 50% negative --> highly balanced

sentiment
positive    0.5
negative    0.5
Name: proportion, dtype: float64

In [ ]:

# cleaning from urls and html tags and normalize repeated spaces

import re

def clean_for_sentiment(t: str) -> str:
    t = str(t).lower()

    t = re.sub(r"http\S+|www\.\S+", " ", t)

    t = re.sub(r"<.*?>", " ", t)

    t = re.sub(r"\s+", " ", t).strip()
    return t

df["review"] = df[text_col].apply(clean_for_sentiment)
df["review"] = df["review"].str.lower() # turn everything to lowercase
df[["review"]].head()

                                              review
0  one of the other reviewers has mentioned that ...
1  a wonderful little production. the filming tec...
2  i thought this was a wonderful way to spend ti...
3  basically there's a family where a little boy ...
4  petter mattei's "love in the time of money" is...

In [7]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [8]:
df.to_csv(CLEANED_PATH)