In [2]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import pandas as pd

CLEANED_PATH = "../data/clean/cleaned_imdb.csv"
MODEL_DATA = "../data/gold/final_imdb.csv"

df = pd.read_csv(CLEANED_PATH)

In [ ]:
analyzer = SentimentIntensityAnalyzer()

vader_score = df["review"].apply(analyzer.polarity_scores) # applying vader polarity
vader_df = pd.DataFrame(list(vader_score))
#  vader is a series of dicts --> we convert it to dataframe
X_vader = vader_df[["neg", "neu", "pos", "compound"]]

X_vader.shape

(50000, 4)

In [ ]:
from textblob import TextBlob

df["tb_polarity"] = df["review"].apply(lambda x : TextBlob(x).sentiment.polarity) # applying textblob
df["tb_subjectivity"] = df["review"].apply(lambda x : TextBlob(x).sentiment.subjectivity)

X_tb= df[["tb_polarity", "tb_subjectivity"]]
X_tb.shape

(50000, 2)

In [ ]:
df = df.drop(columns=["Unnamed: 0"], errors="ignore")
df = pd.concat([df, vader_df], axis=1) # using hybrid approach (vader & textblob)
df.head()

,review,sentiment,tb_polarity,tb_subjectivity,neg,neu,pos,compound
0,one of the other reviewers has mentioned that ...,positive,0.023433,0.490369,0.181,0.754,0.065,-0.9916
1,a wonderful little production. the filming tec...,positive,0.109722,0.559343,0.053,0.765,0.182,0.9670
2,i thought this was a wonderful way to spend ti...,positive,0.360960,0.655933,0.113,0.665,0.222,0.9745
3,basically there's a family where a little boy ...,negative,0.004167,0.459259,0.127,0.813,0.060,-0.9213
4,"petter mattei's ""love in the time of money"" is...",positive,0.214483,0.451359,0.051,0.796,0.153,0.9766

In [13]:
df[["neg", "neu", "pos", "compound", "tb_polarity", "tb_subjectivity"]].agg(["min", "max"])

       neg    neu    pos  compound  tb_polarity  tb_subjectivity
min  0.000  0.339  0.000   -0.9997         -1.0              0.0
max  0.577  1.000  0.523    0.9999          1.0              1.0

In [8]:
df.to_csv(MODEL_DATA)